# Config for TFSec
---
exclude:
  # Terraform Cloud encrypts state at rest
  # https://www.terraform.io/language/state/sensitive-data
  - general-secrets-no-plaintext-exposure
  # Should all be public
  - AVD-GIT-0001