on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Deploy fluent-bit infra
jobs:
  update-infra-common:
    uses: calyptia/fluent-bit-infra/.github/workflows/call-common.yaml@main
    with:
      ignore_errors: true
    secrets:
      gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      terraform_cloud_api_token: ${{ secrets.TF_API_TOKEN }}
      cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
      packet_net_token: ${{ secrets.PACKET_NET_TOKEN }}
      github_personal_access_token: ${{ secrets.GH_PA_TOKEN }}
      github_owner: ${{ secrets.GH_PA_OWNER }}

  update-infra-apply:
      name: Apply infrastructure changes
      needs: update-infra-common
      runs-on: ubuntu-latest
      steps:
      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false -auto-approve
        working-directory: terraform
