name: Import Fluent Bit Infra

on:
  # We only ever want to run manually
  workflow_dispatch:
    inputs:
      import-resource:
        type: string
        description: The resource to import, everything after `terraform import `
        required: true

jobs:
  import:
    name: Update Terraform state by importing existing resources
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.import-resource }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/terraform-setup
        with:
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          terraform_cloud_api_token: ${{ secrets.TF_API_TOKEN }}
          cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
          metal_token: ${{ secrets.PACKET_NET_TOKEN }}
          github_personal_access_token: ${{ secrets.GH_PA_TOKEN }}
          aws_s3_access_id_staging: ${{ secrets.AWS_S3_ACCESS_ID_STAGING }}
          aws_s3_secret_access_key_staging: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_STAGING }}
          gpg_private_key_staging: ${{ secrets.GPG_PRIVATE_KEY_STAGING }}
          aws_s3_access_id_releases: ${{ secrets.AWS_S3_ACCESS_ID_RELEASES }}
          aws_s3_secret_access_key_releases: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_RELEASES }}
          gpg_private_key_releases: ${{ secrets.GPG_PRIVATE_KEY_RELEASES }}
          release-cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Terraform import
        run: |
          terraform import --no-color ${{ github.event.inputs.import-resource }}
        working-directory: terraform